datawarehouse:
  outputs:
    dev:
      dataset: '{{ env_var(''DBT_DATASET'') }}'
      keyfile: '{{ env_var(''DBT_KEYFILE_PATH'') }}'
      location: '{{ env_var(''DBT_LOCATION'') }}'
      method: '{{ env_var(''DBT_METHOD'') }}'
      priority: '{{ env_var(''DBT_PRIORITY'') }}'
      project: '{{ env_var(''DBT_PROJECT'') }}'
      retries: '{{ env_var(''DBT_JOB_RETRIES'') | int }}'
      threads: '{{ env_var(''DBT_THREADS'') | int }}'
      timeout_seconds: '{{ env_var(''DBT_JOB_TIMEOUT'') | int }}'
      type: bigquery
  target: dev
